# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

self-hosted-runner:
  labels:
    # See https://confluence.eng.nutanix.com:8443/pages/viewpage.action?spaceKey=KAR&title=Github+Actions+for+NKP
    - self-hosted-ncn-dind
    - self-hosted-ncn-docker-medium
    - self-hosted-ncn-docker-large
