apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${releaseName}-helmrelease
  namespace: ${releaseNamespace}
spec:
  prune: true
  wait: true
  interval: 6h
  retryInterval: 1m
  path: ./applications/podinfo/6.8.0/helmrelease
  sourceRef:
    kind: OCIRepository
    name: podinfo-6.8.0
    namespace: kommander-flux
  timeout: 1m
