apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${releaseName}-helmrelease
  namespace: ${releaseNamespace}
spec:
  prune: true
  wait: true
  interval: 6h
  retryInterval: 1m
  path: ./helmrelease
  sourceRef:
    kind: OCIRepository
    name: app-${releaseName}
    namespace: kommander-flux
  timeout: 1m
