# Kubernetes versions
# (e.g. 1.35.0 - has to match versions in https://github.com/yannh/kubernetes-json-schema)
k8s_versions:
  - 1.33.0
  - 1.34.0
  - 1.35.0

# use strict validation (reject unknown fields in resources)
strict: true
