apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: podinfo-6.9.1
  namespace: ${releaseNamespace}
spec:
  interval: 10m0s
  ref:
    tag: 6.9.1
  url: oci://ghcr.io/stefanprodan/charts/podinfo
