---
apiVersion: v1
data:
  values.yaml: |
    # publicAddr -- The FQDN users will use to access Kasm Workspaces.
    # Must match the Common Name on your TLS certificate.
    publicAddr: "kasm.example.com"

    # certificate -- TLS certificate configuration.
    # Create a Kubernetes TLS secret and set its name here, or enable cert-manager.
    certificate:
      secretName: "kasm-tls-secret"

    # proxyService -- Set to ClusterIP when using an Ingress or Route.
    proxyService:
      type: ClusterIP

    # ingress -- Configure Ingress to expose Kasm through your cluster ingress controller.
    ingress:
      enabled: true
kind: ConfigMap
metadata:
  name: ${releaseName}-1.1181.0-config-defaults
  namespace: ${releaseNamespace}
