name: Publish OCI Artifacts

on:
  workflow_dispatch:
    inputs:
      release_spec:
        description: "dev uses .release/dev.yaml; stable uses .release/stable.yaml"
        required: true
        type: choice
        options:
          - dev
          - stable
  push:
    branches:
      - main
    paths:
      - ".release/**"
      - "applications/**"

jobs:
  release-artifacts:
    name: Publish OCI Artifacts
    runs-on:
      - self-hosted-ncn-docker-medium
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NIX
        uses: cachix/install-nix-action@v31

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.15.0
        with:
          enable-cache: true
          skip-nix-installation: true

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Dev Release
        if: github.event_name == 'push' || github.event.inputs.release_spec == 'dev'
        run: devbox run -- just publish-artifacts ./.release/dev.yaml ghcr.io/nutanix-cloud-native

      - name: Build Stable Release
        # Production artifacts can be published only on the main branch.
        if: github.ref_name == 'main' && (github.event_name == 'push' || github.event.inputs.release_spec == 'stable')
        run: devbox run -- just publish-artifacts ./.release/stable.yaml ghcr.io/nutanix-cloud-native
